title: Alexander Wood's resume
description:  Alexander Wood's Resume
url: https://alexander-wood.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
